ALTER SESSION SET NLS_DATE_FORMAT = 'MM/DD/SYYYY HH24:MI:SS';
ALTER SESSION SET NLS_TIMESTAMP_TZ_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF TZH:TZM';
ALTER SESSION SET NLS_TIMESTAMP_FORMAT = 'MM/DD/SYYYY HH24:MI:SS.FF';
ALTER SESSION SET NLS_NUMERIC_CHARACTERS = '.,';
ALTER SESSION SET NLS_NCHAR_CONV_EXCP = FALSE;
ALTER SESSION SET TIME_ZONE = '+07:00';

INSERT INTO DRUGS(ID, APPLY_TYPE, NAME, PRICE, STORAGE_QUANTITY, TYPE) VALUES
(102, 'Внутрь', 'Анальгин', 100, 10, 'Обезбаливающие');
INSERT INTO DRUGS(ID, APPLY_TYPE, NAME, PRICE, STORAGE_QUANTITY, TYPE) VALUES
(103, 'Под язык', 'Эргоферон', 400, 2, 'От насморка');

INSERT INTO RECIPES(ID, ADDRESS, AGE, DIAGNOSIS, FIRST_NAME, LAST_NAME, PHONE, SECOND_NAME) VALUES
(83, 'ул. Домовая, д. 2', 50, 'Сильный кашль', 'Крбцев', 'Сергей', '89124356789', 'Николаевич');
INSERT INTO RECIPES(ID, ADDRESS, AGE, DIAGNOSIS, FIRST_NAME, LAST_NAME, PHONE, SECOND_NAME) VALUES
(81, 'ул. Зомбей, д. 1, кв. 2', 33, 'Заражён религией', 'Молдавский', 'Максим', '89131234567', 'Игоревич');
INSERT INTO RECIPES(ID, ADDRESS, AGE, DIAGNOSIS, FIRST_NAME, LAST_NAME, PHONE, SECOND_NAME) VALUES
(82, 'ул. Ленивых, д. 10', 20, 'Лень', 'Иванов', 'Иван', '81234567890', 'Иванович');

INSERT INTO DRUG_ORDERS(ID, DATE_SELL, QUANTITY, TOTAL_PRICE, DRUG_ID, RECIPE_ID) VALUES
(1, '12/10/2015 16:19:30.494468000', 10, 1000, 102, NULL);
INSERT INTO DRUG_ORDERS(ID, DATE_SELL, QUANTITY, TOTAL_PRICE, DRUG_ID, RECIPE_ID) VALUES
(2, '12/07/2015 16:20:17.226032000', 9, 900, 102, 83);

INSERT INTO RESOURCES(ID, NAME, PARENT_RESOURCE_ID) VALUES
(1, 'admin', NULL);
INSERT INTO RESOURCES(ID, NAME, PARENT_RESOURCE_ID) VALUES
(2, 'admin/recipes', 1);
INSERT INTO RESOURCES(ID, NAME, PARENT_RESOURCE_ID) VALUES
(3, 'admin/products', 1);
INSERT INTO RESOURCES(ID, NAME, PARENT_RESOURCE_ID) VALUES
(4, 'admin/sells', 1);
INSERT INTO RESOURCES(ID, NAME, PARENT_RESOURCE_ID) VALUES
(5, 'trader', NULL);
INSERT INTO RESOURCES(ID, NAME, PARENT_RESOURCE_ID) VALUES
(6, 'trader/sell', 5);
INSERT INTO RESOURCES(ID, NAME, PARENT_RESOURCE_ID) VALUES
(7, 'trader/create_recipe', 5);

INSERT INTO USERS(ID, LOGIN, PASSWORDHASH, PERSONNAME, SALT) VALUES
(1, 'admin', '56de704185aefb35d7f7c41f84edb96bbc878f7d', 'Admin Adminov', 'salt');
INSERT INTO USERS(ID, LOGIN, PASSWORDHASH, PERSONNAME, SALT) VALUES
(2, 'trader', '56de704185aefb35d7f7c41f84edb96bbc878f7d', 'Trader Traderov', 'salt');

INSERT INTO RESOURCES_USERS(ID, ROLE, RESOURCE_ID, USER_ID) VALUES
(12, 1, 2, 1);

COMMIT;